[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "JAWSOME"
dynamic = ["version"]
description = "Discover token roles inside AWS environment"
keywords = ["AWS", "IAM", "bruteforce"]
readme = "README.md"
authors = [
    {name = "pasdoue", email = "pasdoue@protonmail.com"},
]
maintainers = [
    {name = "pasdoue", email = "pasdoue@protonmail.com"}
]

requires-python = ">= 3.10"
dependencies = [
    "R2Log~=1.0.2",
    "boto3",
    "botocore",
    "requests~=2.34.2",
    "aiobotocore~=3.7.0",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-cov>=6.0",
]

[project.scripts]
jawsome = "jawsome.main:main"

[project.urls]
Documentation = "https://github.com/pasdoue/JAWS/blob/main/README.md"
Repository = "https://github.com/pasdoue/JAWS"
Issues = "https://github.com/pasdoue/JAWS/issues"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.pdm]
[tool.pdm.version]
source = "file"
path = "jawsome/config/ToolConfig.py"

[tool.pdm.build]
excludes = ["tests"]
